config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  resources :gwas
  resources :consensus_fastqs

  root 'welcome#index'

  namespace :api do
    get 'v1/jsondata'
    get 'v1/rstudiodata'
    get 'v1/genesdata'
    get 'v2/sample'
    get 'v2/hla'
    get 'v2/kir'
    post 'v2/kir_pipeline'
  end

  # namespace :chart do
  #   get 'processing'
  #   get 'index_panel_one_data'
  #   get 'index_panel_two_data'
  #   get 'index_panel_three_data'
  #   get 'index_panel_four_data'
  # end

  get 'topics/index'

  namespace :welcome do
    get 'progress'
    get 'samples_table'
    get 'samples_summary_table'
    get 'dataset_stats'
    get 'dataset'
    get 'collaborator_status'
    get 'site_samples_progress'
    get 'collaborators'
    get 'abstract'
    get 'progress'
    get 'samples_processed'
    get 'immport'
    get 'immport_status_table_data'
  end

  namespace :dataview do
    get 'index'
    get 'superindex'
    get 'superindex_race_graph'
    get 'superindex_sex_graph'
    get 'superindex_age_graph'
    get 'sample_processing_status'
    get 'sample_status'
    get 'samples_index'
    get 'hla_index'
    get 'kir_index'
    get 'samples_superindex'
    get 'hla_superindex'
    get 'kir_superindex'
    get 'modal_content'
    get 'download_sample_data'
    get 'download_hla_data'
    get 'download_kir_data'
    get 'download_hla_data_superuser'
    get 'download_kir_data_superuser'
    get 'download_all_data_superuser'
    get 'download_idr'
    get 'samples_to_json'
    get 'hlas_to_json'
    get 'kirs_to_json'
    get 'single_kir_genotype_version_table'
    get 'single_kir_wip_versions_data'
    get 'superindex_samples_to_json'
    get 'superindex_hlas_to_json'
    get 'superindex_kirs_to_json'
    get 'kir_genotyping_work_in_progress'
    get 'kir_wip_data'
    get 'method_version'
    get 'method_version_data'
    get 'allele_frequencies'
    get 'allele_frequencies_data'
    get 'haplotype_frequencies'
    get 'haplotype_frequecies_data'
  end

  get 'profiles/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # resources 'dataview', only: [:index]

  get 'nmdp_apis/test_gfe'
  
  get '*path', to: 'error#error_404', via: :all, as: 'error'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def next
  end

  def progress
    @collabs = Collaborator.where.not(disease:"SCZD")
  end

  def new_progress
  end

  def site_samples_progress
    @collaborator_id = Collaborator.find_by(name:params[:collaborator]).id
    respond_to do |format|
      format.json { render json: SiteProgressDatatable.new(view_context, @collaborator_id) }
    end
  end

  def collaborator_status
    respond_to do |format|
      format.json { render json: CollaboratorStatusDatatable.new(view_context) }
    end
  end

  def immport
  end

  def immport_status_table_data
    respond_to do |format|
      format.json { render json: ImmportStatusDatatable.new(view_context) }
    end
  end

  def samples_table
  end

  def dataset
    @collaborators = Collaborator.all.reject { |c| c.samples.count < 1 }
    @collaborator = Collaborator.find(params[:collaborator_id])
  end

  def samples_processed
    @Samples = Sample.group(:disease).group(:short_date).count
    render json: @Samples
  end

  def dataset_stats
    @id = params[:collaborator_id].to_i
    @Collaborator = Collaborator.find(@id)
    @all_samples = 0
    @samples_to_stanford = 0
    response = {samples_male_cases:0, samples_female_cases: 0, samples_male_controls:0, samples_female_controls:0, hla_available_male_controls:0, hla_available_female_controls:0, hla_available_male_cases:0, hla_available_female_cases:0, samples_total:0, hla_samples_to_stanford:0}
    if @Collaborator.datasets
      @Collaborator.datasets.all.each do |d|
        @all_samples += d.samples_male_controls + d.samples_female_controls + d.samples_male_cases + d.samples_female_cases
        @samples_to_stanford += d.total_samples_sent_to_stanford

        response[:samples_male_cases] += d.samples_male_cases
        response[:samples_female_cases] += d.samples_female_cases
        response[:samples_male_controls] += d.samples_male_controls
        response[:samples_female_controls] += d.samples_female_controls
        response[:hla_available_male_controls] += d.hla_available_male_controls
        response[:hla_available_female_controls] += d.hla_available_female_controls
        response[:hla_available_male_cases] += d.hla_available_male_cases
        response[:hla_available_female_cases] += d.hla_available_female_cases
      end
      response[:samples_total] = @Collaborator.expected_discovery - @all_samples
      response[:hla_samples_to_stanford] = @samples_to_stanford - response[:hla_available_female_cases] - response[:hla_available_male_cases] - response[:hla_available_female_controls] - response[:hla_available_male_controls]
    else
      response = {'message':'no data for this collaborator'}
    end
    render json: response
  end

  def samples_summary_data
    respond_to do |format|
      result = []
      @datasets = Dataset.all.pluck(:disease, :source, :id)
      @datasets.each do |d|
        @batches = Batch.where(Dataset_id:d[2]).pluck(:hlas_available, :kirs_available, :samples_received_at_ucsf, :samples_sent_to_stanford, :id)
        @batches.each do |b|
          sample_count = Sample.where(batch_id:b[4]).count
          b.push(sample_count)
        end
        d.push(@batches)
        result.push(d)
      end
      format.js {render :json => result}
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_piecharttest.html.erb
<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    // Define the chart to be drawn.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Element');
    data.addColumn('number', 'Percentage');
    data.addRows([
      ["Parkinson's Disease", 3300],
      ["Schizophrenia", 5050],
      ["Neuromyelitis Optica", 1025],
      ["Myasthenia Gravis", 950],
      ["Multiple Sclerosis", 2000],
      ["Healthy Control", 1000]
    ]);

    var options = {
      title: "European Study Subjects",
      is3D: true,
      pieSliceText: "none",
      colors:['#EE1289','#2E37FE','#B0171F','#24D330','orange','#993300'],
      pieStartAngle: '30',
      chartArea:{left:0,top:50,width:'100%',height:'100%'},
      height:'350',
      width:'500',
      legend: {position:'left', textStyle: {fontSize:16}},
      titleTextStyle: {fontSize:20}
    }
    // Instantiate and draw the chart.
    var chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
    chart.draw(data, options);
  }
</script>
<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    // Define the chart to be drawn.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Element');
    data.addColumn('number', 'Percentage');
    data.addRows([
      ["Schizophrenia", 1500],
      ["Neuromyelitis Optica", 530],
      ["Multiple Sclerosis", 2300],
      ["Healthy Control", 1700]
    ]);

    var options = {
      title: "Non-European Study Subjects",
      is3D: true,
      pieSliceText: "none",
      pieSliceTextStyle: {color:'black', size:'16'},
      colors:['#2E37FE','#B0171F','orange','#993300'],
      pieStartAngle: '30',
      chartArea:{left:0,top:50,width:'100%',height:'100%'},
      height:'350',
      width:'500',
      legend: {position:'left', textStyle: {fontSize:16, color:'black'}},
      titleTextStyle: {fontSize:20}
    }
    // Instantiate and draw the chart.
    var chart = new google.visualization.PieChart(document.getElementById('myPieChart2'));
    chart.draw(data, options);
  }
</script>

<script type="text/javascript">
  google.charts.load('current', {'packages':['sankey']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'From');
    data.addColumn('string', 'To');
    data.addColumn('number', 'Weight');
    data.addRows([
      [ 'A', 'X', 5 ],
      [ 'A', 'Y', 7 ],
      [ 'A', 'Z', 6 ],
      [ 'B', 'X', 2 ],
      [ 'B', 'Y', 9 ],
      [ 'B', 'Z', 4 ]
    ]);

    // Sets chart options.
    var options = {
      width: 600,
    };

    // Instantiates and draws our chart, passing in some options.
    var chart = new google.visualization.Sankey(document.getElementById('sankey_basic'));
    chart.draw(data, options);
  }
</script>

<div class="row">
  <div id="myPieChart" class="col-sm-6"></div>
  <div id="myPieChart2" class="col-sm-6"></div>
</div>

app/views/welcome/collaborators.html.erb
<div class="container animated fadeIn welcome-contain">
  <div class="row">
    <div class="col-md-12" style="background-color:#f6f6f6;border-top:1px solid #696969;">
      <ul style="list-style:none;padding-top: 5px;padding-bottom:10px;">
        <li style="float:right;padding-left:10px;"><%= link_to "Abstract", welcome_abstract_path  %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "Collaborators", welcome_collaborators_path, :style => "font-weight:bold; color:#320b59;" %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "Progress", welcome_progress_path %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "About", welcome_next_path %></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" style="background-color:#f6f6f6;height:20px;"></div>
  </div>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1" style="background-color:#ededed; border-bottom: 2px solid #696969">
      <div id="collab-table" style="display:inline; float:right;width:40%"></div>
      <div id="us-map" style="display:inline;margin-bottom:30px;"></div>
      <br>
      <div id="eur-map" style="display:inline;"></div>
    </div>
  </div>
</div>

<script type="text/javascript">

  google.charts.load('upcoming', { packages: ['geochart', 'table'] });

  google.charts.setOnLoadCallback(drawUSMap);

  google.charts.setOnLoadCallback(drawEurMap);

  google.charts.setOnLoadCallback(drawCollaboratorsTable);

  function drawUSMap() {

    var data = google.visualization.arrayToDataTable([
      ['Location', 'Discovery (N)'],
      ['UCSF', 3900],
      ['Michael J Fox Foundation, New York, NY', 1500],
      ['University of Miami', 500],
      ['Guthy-Jackson Foundation, San Diego, CA', 600],
      ['Mayo Clinic, Rochester, MN', 380],
      ['National Institute of Mental Health, Rockville, MD', 1500],
      ['University of Texas-Southwestern, Dallas, TX', 200],
      ['National Instutute on Aging, Bethesda, MD', 2000],
      ['University of Pittsburgh, Pittsburgh, PA', 1500]
    ]);

    var options = {
      region: 'US',
      displayMode: 'markers',
      keepAspectRatio: true,
      colorAxis: {colors: ['red', 'blue']}
    }

    var chart = new google.visualization.GeoChart(document.getElementById('us-map'));
    chart.draw(data, options);
  }

  function drawEurMap() {

    var data = google.visualization.arrayToDataTable([
      ['Location', 'Discovery (N)'],
      ['Karolinksa Insitute', 600],
      ['Oslo University Hospital', 350],
      ['Oslo University', 600],
      ['University of London', 500],
      ['Netherlands', 1000],
      ['UK', 500],
      ['Ireland', 950],
      ['University of the Highlands and Islands, Scotland', 500],
      ['Aberdeen University, Aberdeen, Scotland', 500],
      ['Rheinische Friedrich-Wilhelms-Universität Bonn', 500]
    ]);

    var options = {
      region: '154',
      displayMode: 'markers',
      keepAspectRatio: true,
      colorAxis: {colors: ['red', 'blue']}
    }

    var chart = new google.visualization.GeoChart(document.getElementById('eur-map'));
    chart.draw(data, options);
  }

  function drawCollaboratorsTable() {

    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Population');
    data.addColumn('string', 'Custodian Group');
    data.addColumn('number', 'Discovery (N)');
    data.addRows([
      ['MS White Americans', 'UCSF', 2000],
      ['MS Afican Americans', 'UCSF', 1500],
      ['MS Hispanic Americans', 'University of Miami', 500],
      ['MS Hispanic Americans', 'UCSF', 300],
      ['NMO White Americans', 'Guthy-Jackson Foundation', 450],
      ['NMO White Americans', 'Mayo Clinic', 350],
      ['NMO White Americans', 'UT Southwestern', 100],
      ['NMO White UK', 'Oxford University', 100],
      ['NMO Hispanic Americans', 'Guthy-Jackson Foundation', 90],
      ['NMO African Americans', 'Guthy-Jackson Foundation', 60],
      ['NMO African Americans', 'UCSF/Mayo Clinic', 100],
      ['NMO Asian Americans', 'Mayo Clinic', 30],
      ['NMO Japan', 'Kyushu University', 150],
      ['MG Sweden', 'Karolinska Institute', 600],
      ['MG Norway', 'Oslo University Hospital', 350],
      ['PD White Americans', 'NIH/NIA', 2000],
      ['PD White Americans', 'M.J. Fox Foundation', 1300],
      ['SCZD Norway', 'Oslo University', 600],
      ['SCZD Dutch', 'UCLA', 1000],
      ['SCZD UK', 'University of London', 500],
      ['SCZD Ireland', 'Virginia Commonwealth University', 950],
      ['SCZD Scotland', 'Univ. of Highlands and Islands', 500],
      ['SCZD Scotland', 'Aberdeen University', 500],
      ['SCZD Germany', 'University of Bonn', 500],
      ['SCZD Canada', 'University of Toronto', 500],
      ['SCZD African Americans', 'University of Pittsburgh/NIMH', 1500]
    ]);
    var table = new google.visualization.Table(document.getElementById('collab-table'));
    table.draw(data, {showRowNumber: false, width:'100%'})
  }
</script>

app/views/welcome/dataset.html.erb
<div class="container welcome-contain content-body">

  <div class="row">
    <div class="col-md-9" style="border-top:1px solid #696969;">
      <h2><span id="collaborator-name"><%= @collaborator.name %></span></h2>
    </div>
    <div class="col-md-3" style="border-top:1px solid #696969;">
      <div class="dropdown" style="margin-top:20px;">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" style="width:100%"><%= @collaborator.name %>&nbsp;<span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><%= link_to "All Collaborators", welcome_progress_path %></li>
          <% @collaborators.each do |c| %>
            <li><%= link_to c.name, welcome_dataset_path(collaborator_id: c.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <br>

<%= render 'welcome/partials/site_specific_samples_progress_table' %>

</div>

app/views/welcome/immport.html.erb
<div class="container welcome-contain content-body">

  <div class="row">
    <div class="col-sm-9" style="border-top:1px solid #696969;">
      <h1>Status of INDIGO Data Deposits to Immport</h1>
    </div>
    <div class="col-sm-3" style="border-top:1px solid #696969;">
    </div>
  </div>

  <br>
  <%= render 'welcome/partials/immport_status_table' %>
</div>

app/views/welcome/old_dataset.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-9" style="border-top:1px solid #696969;">
      <h2><%= @collaborator.name %></h2>
      <h4>Proposed Cases and Controls: <%= @collaborator.expected_discovery %></h2>
    </div>
    <div class="col-md-3" style="border-top:1px solid #696969;">
      <div class="dropdown" style="margin-top:20px;">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" style="width:100%"><%= @collaborator.name %>&nbsp;<span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><%= link_to "All Collaborators", welcome_progress_path %></li>
          <% @collaborators.each do |c| %>
            <li><%= link_to c.name, welcome_dataset_path(collaborator_id: c.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <br>

  <% if @datasets.count == 0 %>
    <div class="row">
      <div class="col-md-12" style="margin-top:100px;">
        <h2 class="text-center">No Samples for <%= @collaborator.name %> Have Been Received at UCSF</h2>
      </div>
    </div>
  <% else %>
    <div class="row">
      <hr>
      <div class="col-md-6">
        <h4 class="text-center">Samples Received by Gender, Cases and Controls</h4>
        <div id="pie-chart-1">
        </div>
      </div>
      <div class="col-md-6">
        <h4 class="text-center">HLA Available by Gender, Cases and Controls of Samples Sent to Stanford for Genotyping</h4>
        <div id="pie-chart-2">
        </div>
      </div>
    </div>
  <% end %>

  <%if @datasets.count > 0 %>
    <% gwas_supers = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'] %>
    <% gwas_supers_counter = 0 %>
    <% gwas_footnote = "" %>
    <% gwas_hash = {} %>
    <hr>

    <div class="row">
      <div class="col-md-12">
        <table class="table table-bordered" style="border-top:1px solid #696969;">
          <thead style="background-color:#bdbdbd;">
            <th>Dataset</th>
            <th>Number of Samples</th>
            <th>Date Samples Received at UCSF</th>
            <th>Samples To Be Sequenced For HLA, KIR, or Both</th>
            <th>Cases</th>
            <th>Controls</th>
            <th>Mixed Cases and Controls</th>
            <th>Date Samples Sent to Stanford</th>
            <th>N of Case & Control Samples Sent to Stanford for Sequencing</th>
            <th>N of Case & Control Raw Data Received at UCSF For Genotype Calling (KIR only)</th>
            <th>N of Case & Control Genotypes Finished, with Version Indicated</th>
            <th>N of Samples Covered By GWAS</th>
          </thead>
          <tbody>
            <% @datasets.each do |d| %>
              <% d.batches.each do |b| %>
                <tr>
                  <td><%= d.source %></td>
                  <td><%= number_with_delimiter(b.samples.count, :delimiter => ',') %></td>
                  <td><%= b.date_received_from_source %></td>
                  <td><%= @collaborator.sequence_type %></td>
                  <% if (b.samples_case_male + b.samples_case_female + b.samples_case_gender_unknown).to_i > 0 %>
                    <td><%= number_with_delimiter((b.samples_case_male + b.samples_case_female + b.samples_case_gender_unknown).to_i, :delimiter => ',') %></td>
                  <% else %>
                    <td>-</td>
                  <% end %>
                  <% if b.samples_control_male + b.samples_control_female + b.samples_control_gender_unknown > 0 %>
                    <td><%= number_with_delimiter((b.samples_control_male + b.samples_control_female + b.samples_control_gender_unknown).to_i, :delimiter => ',') %></td>
                  <% else %>
                    <td>-</td>
                  <% end %>
                  <% if b.samples_unknown_disease_male + b.samples_unknown_disease_female + b.samples_unknown_disease_unknown_gender > 0 %>
                    <td><%= number_with_delimiter((b.samples_unknown_disease_male + b.samples_unknown_disease_female + b.samples_unknown_disease_unknown_gender).to_i, :delimiter => ',') %></td>
                  <% else %>
                    <td>-</td>
                  <% end %>
                  <td><%= b.samples_sent_to_stanford %></td>
                  <% if b.to_stanford %>
                    <td><%= number_with_delimiter(b.samples.count, :delimiter => ',') %></td>
                  <% else %>
                    <td>-</td>
                  <% end %>
                  <td></td>
                  <td></td>
                  <% if b.gwas_samples_count > 0 %>
                    <td><%= b.gwas_samples_count %>
                      <% b.gwas.each do |g| %>
                        <% if gwas_hash[g.name] %>
                          <sup><%= gwas_hash[g.name] %></sup>
                        <% else %>
                        <sup><%= gwas_supers[gwas_supers_counter] %></sup>
                          <!-- <% gwas_footnote += "#{gwas_supers[gwas_supers_counter]}: #{g.name}; " %> -->
                          <% gwas_hash[g.name] = gwas_supers[gwas_supers_counter] %>
                          <% gwas_supers_counter += 1 %>
                        <% end %>
                      <% end %>
                    </td>
                  <% else %>
                    <td>-</td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <h6 class="text-right" style="font-weight:bold;">
          <% gwas_hash.each do |k, v| %>
            <% url = Gwas.find_by(name:k).url %>
            <%= v %>: <%= link_to k, url, :style =>"text-decoration:underline;" %>;
          <% end %>
        </h6>
      </div>
    </div>
  <% end %>

</div>

<script>

  google.charts.load('current', { 'packages':['corechart']});

    var collaborator_id = window.location.href.split('=')[1];

    $.get('<%= Rails.application.routes.url_helpers.welcome_dataset_stats_path %>', {collaborator_id: collaborator_id}, function(response){

      var prettyPrint = {
        samples_male_cases: "male cases",
        samples_female_cases: "female cases",
        samples_male_controls: "male controls",
        samples_female_controls: "female controls",
        samples_total: "total",
        hla_available_male_cases: "male cases",
        hla_available_female_cases: "female cases",
        hla_available_male_controls: "male controls",
        hla_available_female_controls: "female controls",
        hla_samples_to_stanford: "to stanford"
      }
      var dataMatrix1 = [['Gender/Case or Control', 'Samples'], ["male cases"], ["female cases"] ,["male controls"], ["female controls"], ["not received or case/control not indicated"]];
      var dataMatrix2 = [['Gender/Case or Control', 'HLA available'], ["male cases"], ["female cases"] ,["male controls"], ["female controls"], ['sample not genotyped']];
      for (key in response) {
        if (key.split('_')[0] === "samples") {
          switch(prettyPrint[key]) {
            case 'male cases':
              dataMatrix1[1].push(response[key])
              break;
            case 'female cases':
              dataMatrix1[2].push(response[key]);
              break;
            case 'male controls':
              dataMatrix1[3].push(response[key]);
              break;
            case 'female controls':
              dataMatrix1[4].push(response[key]);
              break;
            case 'total':
              dataMatrix1[5].push(response[key]);
              break;
          }
        }
        else {
          switch(prettyPrint[key]) {
            case 'male cases':
              dataMatrix2[1].push(response[key])
              break;
            case 'female cases':
              dataMatrix2[2].push(response[key]);
              break;
            case 'male controls':
              dataMatrix2[3].push(response[key]);
              break;
            case 'female controls':
              dataMatrix2[4].push(response[key]);
              break;
            case 'to stanford':
              dataMatrix2[5].push(response[key]);
              break;
          }
        }
      }

      if (dataMatrix1[5][1] < 0) {
        dataMatrix1.pop();
      }

      function drawFirstChart() {
        var data = google.visualization.arrayToDataTable(dataMatrix1);
        var options = {
          colors: ['#4c177d','#663096','#7647a2','#aa8cc5','#ccbadc'],
          pieSliceText:'value',
          legend: { position:'bottom', alignment:'center', textStyle: {fontSize: 12}, maxLines: '2' },
          height: '350',
          chartArea: {width: '100%', height: '90%', top:'5'},
          is3D:true
        }
        var chart = new google.visualization.PieChart(document.getElementById('pie-chart-1'));
        chart.draw(data, options);
      }
      function drawSecondChart() {
        var data = google.visualization.arrayToDataTable(dataMatrix2);
        var options = {
          colors: ['#4c177d','#663096','#7647a2','#aa8cc5','#ccbadc'],
          pieSliceText:'value',
          legend: { position:'bottom', alignment:'center', textStyle: {fontSize: 12} },
          height: '350',
          chartArea: {width: '100%', height: '90%', top:'5'},
          is3D:true
        }
        var chart = new google.visualization.PieChart(document.getElementById('pie-chart-2'));
        chart.draw(data, options);
      }

        google.charts.setOnLoadCallback(drawFirstChart);
        google.charts.setOnLoadCallback(drawSecondChart);



    })

</script>

app/views/welcome/progress.html.erb
<div class="container welcome-contain content-body">

  <div class="row">
    <div class="col-sm-9" style="border-top:1px solid #696969;">
      <h1>Progress of Sample Acquistion and Processing</h1>
    </div>
    <div class="col-sm-3" style="border-top:1px solid #696969;">
      <div class="dropdown" style="margin-top:20px;">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" style="width:100%">Select an INDIGO Site&nbsp;<span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><%= link_to "All Collaborators", welcome_progress_path %></li>
          <% @collabs.each do |c| %>
            <li><%= link_to c.name, welcome_dataset_path(collaborator_id: c.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <br>
  <%= render 'welcome/partials/sample_processing_table' %>
</div>

app/views/welcome/samples_table.html.erb
<div class="container animated fadeIn welcome-contain">

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1" style="background-color:#f6f6f6;border-top:1px solid #696969;">
      <ul style="list-style:none;padding-top: 5px;padding-bottom:10px;">
        <li style="float:right;padding-left:10px;"><%= link_to "Abstract", welcome_abstract_path  %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "Collaborators", welcome_collaborators_path %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "Progress", welcome_progress_path, :style => "font-weight:bold; color:#320b59;" %></li>
        <li style="float:right;padding-left:10px;"><%= link_to "About", welcome_next_path %></li>
      </ul>
      <br>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1" style="background-color:#f6f6f6;border-bottom:2px solid #696969">
      <table class="table table-bordered">
        <thead style="background-color:skyblue;">
          <tr>
            <th>Source</th>
            <th>Disease</th>
            <th>Samples Received by UCSF</th>
            <th>Samples In Process at Stanford</th>
            <th>HLA data available</th>
            <th>KIR data available</th>
          </tr>
        </thead>
        <tbody id="table-body" style="background-color:white;">
        </tbody>
      </table>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>
<script>
  $.get("<%= Rails.application.routes.url_helpers.welcome_samples_summary_data_path %>").done(function(response) {
    console.log(response);
    var samples_received_total = 0; var samples_in_process_total = 0; var hlas_available_total = 0; var kirs_available_total = 0;
    response.forEach(function(array) {
      samples_received_total += array.samples_received_at_ucsf;
      samples_in_process_total += array.samples_in_process_at_stanford;
      hlas_available_total += array.hlas_available;
      kirs_available_total += array.kirs_available;
      var hla_count = array.hlas_available ? array.hlas_available : 0
      var kir_count = array.kirs_available ? array.kirs_available : 0
      var row = "<tr><th>"+array.source+"</th><td>"+array.disease+"</td><td>"+array.samples_received_at_ucsf+"</td><td>"+array.samples_in_process_at_stanford+"</td><td>"+hla_count+"</td><td>"+kir_count+"</td></tr>";
      $('#table-body').append(row);
    });

    $('#table-body').append('<tr><th>Total</th><td style="background-color:#f6f6f6";></td><th>'+samples_received_total+'</th><th>'+samples_in_process_total+'</th><th>'+hlas_available_total+'</th><th>'+kirs_available_total+'</th></tr>')

  })
</script>