config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  resources :gwas
  resources :consensus_fastqs

  root 'welcome#index'

  namespace :api do
    get 'v1/jsondata'
    get 'v1/rstudiodata'
    get 'v1/genesdata'
    get 'v2/sample'
    get 'v2/hla'
    get 'v2/kir'
    post 'v2/kir_pipeline'
  end

  # namespace :chart do
  #   get 'processing'
  #   get 'index_panel_one_data'
  #   get 'index_panel_two_data'
  #   get 'index_panel_three_data'
  #   get 'index_panel_four_data'
  # end

  get 'topics/index'

  namespace :welcome do
    get 'progress'
    get 'samples_table'
    get 'samples_summary_table'
    get 'dataset_stats'
    get 'dataset'
    get 'collaborator_status'
    get 'site_samples_progress'
    get 'collaborators'
    get 'abstract'
    get 'progress'
    get 'samples_processed'
    get 'immport'
    get 'immport_status_table_data'
  end

  namespace :dataview do
    get 'index'
    get 'superindex'
    get 'superindex_race_graph'
    get 'superindex_sex_graph'
    get 'superindex_age_graph'
    get 'sample_processing_status'
    get 'sample_status'
    get 'samples_index'
    get 'hla_index'
    get 'kir_index'
    get 'samples_superindex'
    get 'hla_superindex'
    get 'kir_superindex'
    get 'modal_content'
    get 'download_sample_data'
    get 'download_hla_data'
    get 'download_kir_data'
    get 'download_hla_data_superuser'
    get 'download_kir_data_superuser'
    get 'download_all_data_superuser'
    get 'download_idr'
    get 'samples_to_json'
    get 'hlas_to_json'
    get 'kirs_to_json'
    get 'single_kir_genotype_version_table'
    get 'single_kir_wip_versions_data'
    get 'superindex_samples_to_json'
    get 'superindex_hlas_to_json'
    get 'superindex_kirs_to_json'
    get 'kir_genotyping_work_in_progress'
    get 'kir_wip_data'
    get 'method_version'
    get 'method_version_data'
    get 'allele_frequencies'
    get 'allele_frequencies_data'
    get 'haplotype_frequencies'
    get 'haplotype_frequecies_data'
  end

  get 'profiles/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # resources 'dataview', only: [:index]

  get 'nmdp_apis/test_gfe'
  
  get '*path', to: 'error#error_404', via: :all, as: 'error'
end

app/models/consensus_fastq.rb
class ConsensusFastq < ApplicationRecord
end

app/controllers/consensus_fastqs_controller.rb
class ConsensusFastqsController < ApplicationController
  before_action :set_consensus_fastq, only: [:show, :edit, :update, :destroy]

  respond_to :html


  def test_api
    @urlstring_to_post
    @result = HTTParty.post("http://sandypoint.ucsf.edu:8080/gfe",
                            :body => {
                                       :locus => 'HLA-A',
                                       :sequence => 'tacgtacg'
                            }.to_json,
                            :headers => { 'Content-Type' => 'application/json' } )

  puts @result
  end



  def index
    @consensus_fastqs = ConsensusFastq.all
    respond_with(@consensus_fastqs)
  end

  def show
    respond_with(@consensus_fastq)
  end

  def new
    @consensus_fastq = ConsensusFastq.new
    respond_with(@consensus_fastq)
  end

  def edit
  end

  def create
    @consensus_fastq = ConsensusFastq.new(consensus_fastq_params)
    @consensus_fastq.save
    respond_with(@consensus_fastq)
  end

  def update
    @consensus_fastq.update(consensus_fastq_params)
    respond_with(@consensus_fastq)
  end

  def destroy
    @consensus_fastq.destroy
    respond_with(@consensus_fastq)
  end

  private
    def set_consensus_fastq
      @consensus_fastq = ConsensusFastq.find(params[:id])
    end

    def consensus_fastq_params
      params.require(:consensus_fastq).permit(:INDIGO_ID, :gene, :fastq)
    end
end

app/helpers/consensus_fastqs_helper.rb
module ConsensusFastqsHelper
end

app/views/consensus_fastqs/_form.html.erb
<%= form_for(consensus_fastq) do |f| %>
  <% if consensus_fastq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consensus_fastq.errors.count, "error") %> prohibited this consensus_fastq from being saved:</h2>

      <ul>
      <% consensus_fastq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :INDIGO_ID %>
    <%= f.text_field :INDIGO_ID %>
  </div>

  <div class="field">
    <%= f.label :gene %>
    <%= f.text_field :gene %>
  </div>

  <div class="field">
    <%= f.label :fastq %>
    <%= f.text_area :fastq %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consensus_fastqs/edit.html.erb
<h1>Editing Consensus Fastq</h1>

<%= render 'form', consensus_fastq: @consensus_fastq %>

<%= link_to 'Show', @consensus_fastq %> |
<%= link_to 'Back', consensus_fastqs_path %>

app/views/consensus_fastqs/index.html.erb
<div class="container">


  <p id="notice"><%= notice %></p>

  <h1>KIR Informatics</h1>

  To be added:
  <ul>
  <li>Load/search our KIR consensus fastq, w/ PING metadata</li>
  <li>Send an individual KIR fastq to locally hosted GFE and view results in place</li>
  <li>Assemble a bach of KIR fastq and send to GFE service</li>
  <li>Send an individual KIR gl string to NMDP GL string service and store UUID in database</li>
  </ul>


  <table border="1">
    <thead>
      <tr>
        <th>Indigo id</th>
        <th>Gene</th>
        <th>Fastq</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @consensus_fastqs.each do |consensus_fastq| %>
        <tr>
          <td><%= consensus_fastq.INDIGO_ID %></td>
          <td><%= consensus_fastq.gene %></td>
          <td><textarea rows="10" cols="100"><%= consensus_fastq.fastq %></textarea></td>
          <td><%= link_to 'Show', consensus_fastq %></td>

          <% if current_user.has_role? :admin %>
          <td><%= link_to 'Edit', edit_consensus_fastq_path(consensus_fastq) %></td>
          <td><%= link_to 'Destroy', consensus_fastq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>

          <td><%= link_to 'test_gfe', nmdp_apis_test_gfe_path, :'data-toggle' => "tooltip", :'data-placement' => 'bottom', :'title' => "Send this sequence to the  UCSF GFE service" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Consensus Fastq', new_consensus_fastq_path %>

</div>

app/views/consensus_fastqs/new.html.erb
<div class="container">

<h1>New Consensus Fastq</h1>

<%= render 'form', consensus_fastq: @consensus_fastq %>

<%= link_to 'Back', consensus_fastqs_path %>

</div>

app/views/consensus_fastqs/show.html.erb
<div class="container">



<p id="notice"><%= notice %></p>

<p>
  <strong>Indigo id:</strong>
  <%= @consensus_fastq.INDIGO_ID %>
</p>

<p>
  <strong>Gene:</strong>
  <%= @consensus_fastq.gene %>
</p>

<p>
  <strong>Fastq:</strong>
  <%= @consensus_fastq.fastq %>
</p>

<%= link_to 'Edit', edit_consensus_fastq_path(@consensus_fastq) %> |
<%= link_to 'Back', consensus_fastqs_path %>

</div>