config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  resources :gwas
  resources :consensus_fastqs

  root 'welcome#index'

  namespace :api do
    get 'v1/jsondata'
    get 'v1/rstudiodata'
    get 'v1/genesdata'
    get 'v2/sample'
    get 'v2/hla'
    get 'v2/kir'
    post 'v2/kir_pipeline'
  end

  # namespace :chart do
  #   get 'processing'
  #   get 'index_panel_one_data'
  #   get 'index_panel_two_data'
  #   get 'index_panel_three_data'
  #   get 'index_panel_four_data'
  # end

  get 'topics/index'

  namespace :welcome do
    get 'progress'
    get 'samples_table'
    get 'samples_summary_table'
    get 'dataset_stats'
    get 'dataset'
    get 'collaborator_status'
    get 'site_samples_progress'
    get 'collaborators'
    get 'abstract'
    get 'progress'
    get 'samples_processed'
    get 'immport'
    get 'immport_status_table_data'
  end

  namespace :dataview do
    get 'index'
    get 'superindex'
    get 'superindex_race_graph'
    get 'superindex_sex_graph'
    get 'superindex_age_graph'
    get 'sample_processing_status'
    get 'sample_status'
    get 'samples_index'
    get 'hla_index'
    get 'kir_index'
    get 'samples_superindex'
    get 'hla_superindex'
    get 'kir_superindex'
    get 'modal_content'
    get 'download_sample_data'
    get 'download_hla_data'
    get 'download_kir_data'
    get 'download_hla_data_superuser'
    get 'download_kir_data_superuser'
    get 'download_all_data_superuser'
    get 'download_idr'
    get 'samples_to_json'
    get 'hlas_to_json'
    get 'kirs_to_json'
    get 'single_kir_genotype_version_table'
    get 'single_kir_wip_versions_data'
    get 'superindex_samples_to_json'
    get 'superindex_hlas_to_json'
    get 'superindex_kirs_to_json'
    get 'kir_genotyping_work_in_progress'
    get 'kir_wip_data'
    get 'method_version'
    get 'method_version_data'
    get 'allele_frequencies'
    get 'allele_frequencies_data'
    get 'haplotype_frequencies'
    get 'haplotype_frequecies_data'
  end

  get 'profiles/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # resources 'dataview', only: [:index]

  get 'nmdp_apis/test_gfe'
  
  get '*path', to: 'error#error_404', via: :all, as: 'error'
end

app/controllers/dataview_controller.rb
class DataviewController < ApplicationController
  before_action :authenticate_user! #Devise authentication. Resource should only be available to logged in users
   #Cancancan enforces access on the model level. This hash prevents unauthorized users from accessing this resource by blocking this route.
  @sv = "DEFAULT"
  def index
    @samples = Sample.where(sample_source: current_user.affiliation).order("indigo_id ASC")
    @indigo_ids = Sample.where(sample_source: current_user.affiliation).distinct.pluck(:indigo_id)
    @hlas = Hla.where(indigo_id:@indigo_ids).order("indigo_id ASC")
    @kirs = Kir.where(indigo_id:@indigo_ids).order("indigo_id ASC")
  end

  def superindex
    if !current_user.has_role? :superuser
      redirect_to '/dataview#index'
    elsif !dataview_params || !dataview_params[:disease]
      @target = "unknown"
    else
      longform_names = { :PD => "Parkinson's Disease", :MS => "Multiple Sclerosis", :MG => "Myasthenia Gravis", :NMO => "Neuromyelitis Optica", :ALS => "Amyotrophic Lateral Sclerosis", :HC => "Unaffected Controls", :SCZD => "Schizophrenia", :'Not MS - Unaffected - Related' => "Unaffected MS-related", :PANS => "Pediatric Acute-onset Neuropsychiatric Syndrome" }
      if dataview_params[:disease].size == 1
        @disease = dataview_params[:disease][0]
        @header_content = longform_names[@disease.to_sym]
      else
        @disease = dataview_params[:disease].join(",")
        @disease_sym = dataview_params[:disease][0]
        @header_content = longform_names[@disease_sym.to_sym]
      end
    end
  end

  def superindex_race_graph
    @dis = /,/.match(dataview_params[:disease][0]) ? dataview_params[:disease][0].split(",") : dataview_params[:disease]
    races = Sample.where(disease:@dis).where.not(race:nil).pluck(:race).uniq
    output = races.map { |r|
      {:race => r, :samples => Sample.where(disease:@dis).where(race:r).count}
    }
    output.sort_by { |hsh| hsh[:race] }
    if Sample.where(disease:@dis).where(race:nil).count > 0
      output.push({:race => 'NA', :samples => Sample.where(disease:@dis).where(race:nil).count})
    end
    puts output
    render json: output, status: :ok
  end

  def superindex_sex_graph
    @dis = /,/.match(dataview_params[:disease][0]) ? dataview_params[:disease][0].split(",") : dataview_params[:disease]
    longform_names = {:F => "Female", :M => "Male"}
    sexes = Sample.where(disease:@dis).where.not(gender:nil).pluck(:gender).uniq
    sexes = sexes.map(&:downcase)
    sexes.uniq!
    output = sexes.map { |s|
        {:sex => longform_names[s.to_sym], :samples => Sample.where(disease:@dis).where(gender:s).count}
    }
    if Sample.where(disease:@dis).where(gender:nil).count > 0
      output.push({:sex => 'NA', :samples => Sample.where(disease:@dis).where(gender:nil).count})
    end
    render json: output, status: :ok
  end

  def superindex_age_graph
    @dis = /,/.match(dataview_params[:disease][0]) ? dataview_params[:disease][0].split(",") : dataview_params[:disease]
    set_min = Sample.where(disease:@dis).where.not(age_of_onset:nil).pluck(:age_of_onset).uniq.min
    set_max = Sample.where(disease:@dis).where.not(age_of_onset:nil).pluck(:age_of_onset).uniq.max
    min_age = set_min
    max_age = min_age % 10 == 0 ? min_age + 10 : min_age + (10 - (min_age % 10))

    output = []
    while min_age < set_max
      output.push({:range => "#{min_age} - #{max_age}", :samples => Sample.where(disease:@dis).where("age_of_onset >= ?", min_age).where("age_of_onset <= ?", max_age).count })
      min_age = max_age + 1
      max_age = max_age + 10
    end
    if Sample.where(disease:@dis).where(age_of_onset:nil).count > 0
      output.push({:range => "NA", :samples => Sample.where(disease:@dis).where(age_of_onset:nil).count})
    end
    render json: output, status: :ok
  end

  def kir_genotyping_work_in_progress
    unless current_user.is_kir_bioinformatician?
      redirect_to root_path
    end
    @versions = KirGenotypeWip.pluck(:method_version).uniq
  end

  def single_kir_genotype
    indigo_id = params[:id].split("_")[0]
    locus = params[:id].split("_")[1]
    # these @ variables are to set values in the DOM, to be read by the datatable initializer in dataview.js.erb
    @indigo_id = indigo_id
    @gene = locus
    @kir_wips = KirGenotypeWip.where(indigo_id:indigo_id, locus:locus).order("locus ASC").order("method ASC")
  end

  def single_kir_genotype_version_table
    @sample_indigo_id = params[:indigo_id]
    @sample_locus = params[:locus]
  end

  def single_kir_wip_versions_data
    respond_to do |format|
      format.html
      format.json { render json: SingleKirWipVersionsDatatable.new(view_context, params[:indigo_id], params[:locus]) }
    end
  end

  def kir_wip_data
    respond_to do |format|
      format.html
      format.json { render json: KirWipDatatable.new(view_context)}
    end
  end

  def method_version
    unless current_user.is_kir_bioinformatician?
      redirect_to root_path
    end
    @current_version = params[:method_version]
    @versions = KirGenotypeWip.pluck(:method_version).uniq
  end

  def method_version_data
    respond_to do |format|
      format.html
      format.json { render json: MethodVersionDatatable.new(view_context, params[:method_version])}
    end
  end

  def kw_sg_am_data
    puts params[:indigo_id]
    puts params[:gene]
    respond_to do |format|
      format.html
      format.json { render json: KwSgAmDatatable.new(view_context, params[:indigo_id], params[:gene]) }
    end
  end

  def sample_processing_status
    unless current_user.has_role? :superuser
      redirect_to root_path
    end
  end

  def sample_status
    respond_to do |format|
      format.json { render json: SampleDatatable.new(view_context) }
    end
  end

  def samples_index
    respond_to do |format|
      format.json { render json: SampleIndexDatatable.new(view_context, current_user.affiliation) }
    end
  end

  def hla_index
    respond_to do |format|
      format.json { render json: HlaIndexDatatable.new(view_context, current_user.affiliation) }
    end
  end

  def kir_index
    respond_to do |format|
      format.json { render json: KirIndexDatatable.new(view_context, current_user.affiliation) }
    end
  end

  def samples_superindex
    disease = params[:disease]
    respond_to do |format|
      format.json { render json: SampleSuperindexDatatable.new(view_context, disease) }
    end
  end

  def hla_superindex
    disease = params[:disease]
    respond_to do |format|
      format.json { render json: HlaSuperindexDatatable.new(view_context, disease) }
    end
  end

  def kir_superindex
    disease = params[:disease]
    respond_to do |format|
      format.json { render json: KirV2SuperindexDatatable.new(view_context, disease) }
    end
  end

  def modal_content
    puts params[:indigo_id]
    @sample_id = Sample.find_by(indigo_id:params[:indigo_id]).sample_source_identifier
    respond_to do |format|
      format.json { render json: {"study_id": @sample_id} }
    end
  end

  def allele_frequencies
    unless current_user.has_role? :superuser
      redirect_to root_path
    end
  end

  def allele_frequencies_data
    respond_to do |format|
      format.json { render json: AlleleFrequenciesDatatable.new(view_context) }
    end
  end

  def haplotype_frequencies

  end

  def haplotype_frequencies_data
# pass the haplotype scope as a second parameter to the Datatable instantiation
  end

  def samples_to_json
    @samples = Sample.where(sample_source: current_user.affiliation)
    render json: @samples
  end

  def superindex_samples_to_json
    @samples = Sample.all
    render json: @samples
  end

  def hlas_to_json
    @indigo_ids = Sample.where(sample_source: current_user.affiliation).distinct.pluck(:indigo_id)
    @hlas = Hla.where(indigo_id: @indigo_ids)
    render json: @hlas
  end

  def superindex_hlas_to_json
    @hlas = Hla.all
    render json: @hlas
  end

  def kirs_to_json
    @indigo_ids = Sample.where(sample_source: current_user.affiliation).distinct.pluck(:indigo_id)
    @kirs = Kir.where(indigo_id: @indigo_ids)
    render json: @kirs
  end

  def superindex_kirs_to_json
    @kirs = Kir.all
    render json: @kirs
  end

  def download_sample_data
    puts @sv
    @samples = Sample.all
    # respond_to do |format|
    #   format.csv { send_data @samples.master_samples_table_to_csv }
    # end
  end

  def download_hla_data
    @samples = Sample.where(sample_source: current_user.affiliation)
    respond_to do |format|
      format.csv { send_data @samples.to_csv_with_hla }
    end
  end

  def download_kir_data
    @samples = Sample.where(sample_source: current_user.affiliation)
    respond_to do |format|
      format.csv { send_data @samples.to_csv_with_kir }
    end
  end

  def download_hla_data_superuser
    @samples = Sample.all
    respond_to do |format|
      format.csv { send_data @samples.to_csv_with_hla }
    end
  end

  def download_kir_data_superuser
    @samples = Sample.all
    respond_to do |format|
      format.csv { send_data @samples.to_csv_with_kir }
    end
  end

  def download_all_data_superuser
    @samples = Sample.all
    respond_to do |format|
      format.csv { send_data @samples.to_csv_with_hla_and_kir }
    end
  end

  private

    def dataview_params
      params.permit(:disease => [])
    end


end

app/helpers/dataview_helper.rb
module DataviewHelper
end

app/views/dataview/partials/_dataset_graphs.html.erb
<div class="tab-pane fade" id="graphs">
  <div class="row">
    <br></br>

    <div class="col-lg-3">
      <div id="sex-graph"  class="dataset-graph-container"></div>
    </div>
    <div class="col-lg-5">
      <div id="race-graph" class="dataset-graph-container"></div>
    </div>
    <div class="col-lg-3">
      <div id="age-graph"  class="dataset-graph-container"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div id="" class="dataset-graph-container"></div>
    </div>
  </div>
</div>

app/views/dataview/partials/_disease_selector_menu.html.erb
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="disease-dropdown-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="width:100%;">
        Select disease
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="disease-dropdown-menu">
        <li><%= link_to "amyotrophic lateral sclerosis", dataview_superindex_path(disease:["ALS"]) %></li>
        <li><%= link_to "multiple sclerosis", dataview_superindex_path(disease:["MS"]) %></li>
        <li><%= link_to "myasthenia gravis", dataview_superindex_path(disease:["MG"]) %></li>
        <li><%= link_to "neuromyelitis optica", dataview_superindex_path(disease:["NMO"]) %></li>
        <li><%= link_to "Parkinson's disease", dataview_superindex_path(disease:["PD"]) %></li>
        <li><%= link_to "pediatric acute-onset neuropsychiatric syndrome", dataview_superindex_path(disease:["PANS"]) %></li>
        <li class="divider"></li>
        <li><%= link_to "unaffected control", dataview_superindex_path(disease:["HC","Not MS - Unaffected - Unrelated - Spouse"]) %></li>
        <li><%= link_to "unaffected ms-related", dataview_superindex_path(disease:["Not MS - Unaffected - Related","Not MS - unaffected - related"]) %></li>
        <li class="divider"></li>
        <li><%= link_to "allele frequencies", dataview_allele_frequencies_path %></li>
        <%# <li><%= link_to "haplotype frequencies", dataview_haplotype_frequencies_path </li> %>
    </ul>
</div>

app/views/dataview/partials/_hla_datatable.html.erb
<div class="tab-pane fade" id="hla">
  <div class="row" style="border:1px solid #ededed;border-top:none;background-color:#fdfdfd;padding-bottom:10px;overflow-x:scroll;">
    <div class="col-sm-12">
      <br>
      <div class="row">
        <div class="col-sm-12">
          <table id="hla-table-checkbox">
            <caption>check/uncheck boxes to show/hide columns</caption>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=0 data-table-id="hlas-superindex-table" checked=true>INDIGO ID&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=1 data-table-id="hlas-superindex-table" checked=true>Source&nbsp;&nbsp;</label>
              </td>
            </tr>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="2,3" data-table-id="hlas-superindex-table" checked=true>DRB1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="4,5" data-table-id="hlas-superindex-table" checked=true>DQB1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="6,7" data-table-id="hlas-superindex-table" checked=true>DPB1&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="8,9" data-table-id="hlas-superindex-table" checked=true>A&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="10,11" data-table-id="hlas-superindex-table" checked=true>B&nbsp;&nbsp;</label>
              </td>
            </tr>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="12,13" data-table-id="hlas-superindex-table" checked=true>C</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="14,15" data-table-id="hlas-superindex-table" checked=true>DPA1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="16,17" data-table-id="hlas-superindex-table" checked=true>DQA1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column="18,19" data-table-id="hlas-superindex-table" checked=true>DRBo&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=20 data-table-id="hlas-superindex-table" checked=true>DPB1 phase ambiguities</label>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <br>
      <table id="hlas-superindex-table" class="table table-striped table-bordered" data-source="<%= dataview_hla_superindex_url(format:"json") %>" >
        <thead>
        <tr>
          <th>INDIGO ID</th>
          <th>Sample Source</th>
          <th>DRB1/1</th>
          <th>DRB1/2</th>
          <th>DQB1/1</th>
          <th>DQB1/2</th>
          <th>DPB1/1</th>
          <th>DPB1/2</th>
          <th>A/1</th>
          <th>A/2</th>
          <th>B/1</th>
          <th>B/2</th>
          <th>C/1</th>
          <th>C/2</th>
          <th>DPA1/1</th>
          <th>DPA1/2</th>
          <th>DQA1/1</th>
          <th>DQA1/2</th>
          <th>DRBo/1</th>
          <th>DRBo/2</th>
          <th>DPB1 phase ambiguities</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dataview/partials/_kir_datatable.html.erb
<div class="tab-pane fade" id="kir">
  <div class="row" style="border:1px solid #ededed;border-top:none;background-color:#fdfdfd;padding-bottom:10px;overflow-x:scroll;">
    <div class="col-sm-12">
      <br>
      <div class="row">
        <div class="col-sm-12">
          <table id="kir-table-checkbox">
            <caption>check/uncheck boxes to show/hide columns</caption>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=0 data-table-id="kirs-superindex-table" checked=true>INDIGO ID</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=1 data-table-id="kirs-superindex-table" checked=true>Source</label>
              </td>
            </tr>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=2 data-table-id="kirs-superindex-table" checked=true>2DL1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=3 data-table-id="kirs-superindex-table" checked=true>2DL2</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=4 data-table-id="kirs-superindex-table" checked=true>2DL3</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=5 data-table-id="kirs-superindex-table" checked=true>2DL4</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=6 data-table-id="kirs-superindex-table" checked=true>2DL5A</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=7 data-table-id="kirs-superindex-table" checked=true>2DL5B</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=8 data-table-id="kirs-superindex-table" checked=true>2DP1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=9 data-table-id="kirs-superindex-table" checked=true>2DS1</label>
              </td>
            </tr>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=10 data-table-id="kirs-superindex-table" checked=true>2DS2</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=11 data-table-id="kirs-superindex-table" checked=true>2DS3</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=12 data-table-id="kirs-superindex-table" checked=true>2DS4</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=13 data-table-id="kirs-superindex-table" checked=true>2DS5</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=14 data-table-id="kirs-superindex-table" checked=true>3DL1</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=15 data-table-id="kirs-superindex-table" checked=true>3DL2</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=16 data-table-id="kirs-superindex-table" checked=true>3DL3</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=17 data-table-id="kirs-superindex-table" checked=true>3DS1</label>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <br>
      <table id="kirs-superindex-table" class="table table-striped table-bordered" data-source="<%= dataview_kir_superindex_url(format:"json") %>" >
        <thead>
        <tr>
          <th>INDIGO ID</th>
          <th>Sample Source</th>
          <th>KIR2DL1</th>
          <th>KIR2DL2</th>
          <th>KIR2DL3</th>
          <th>KIR2DL4</th>
          <th>KIR2DL5A</th>
          <th>KIR2DL5B</th>
          <th>KIR2DP1</th>
          <th>KIR2DS1</th>
          <th>KIR2DS2</th>
          <th>KIR2DS3</th>
          <th>KIR2DS4</th>
          <th>KIR2DS5</th>
          <th>KIR3DL1</th>
          <th>KIR3DL2</th>
          <th>KIR3DL3</th>
          <th>KIR3DS1</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div> <!-- closes kir table tab-pane -->

app/views/dataview/partials/_samples_datatable.html.erb
<div class="tab-pane fade in active" id="sample">
  <div class="row" style="border:1px solid #ededed;border-top:none;background-color:#fdfdfd;padding-bottom:10px;">
    <div class="col-sm-12">
      <br>
      <div class="row">
        <div class="col-sm-12">
          <table id="sample-table-checkbox">
            <caption>check/uncheck boxes to show/hide columns</caption>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=0 data-table-id="samples-superindex-table" checked=true>INDIGO ID&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=1 data-table-id="samples-superindex-table" checked=true>Source&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=2 data-table-id="samples-superindex-table" checked=true>Site ID</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=3 data-table-id="samples-superindex-table" checked=true>Disease</label>
              </td>
            </tr>
            <tr>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=4 data-table-id="samples-superindex-table" checked=true>Sex</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=5 data-table-id="samples-superindex-table" checked=true>Race</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=6 data-table-id="samples-superindex-table" checked=true>Age of Onset&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=7 data-table-id="samples-superindex-table" checked=true>Age at Sample&nbsp;&nbsp;</label>
              </td>
              <td>
                <label class="checkbox-inline"><input type="checkbox" value="" class="show-column-checkbox" data-column=8 data-table-id="samples-superindex-table" checked=true>Legacy KIR genotype</label>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <br>
      <table id="samples-superindex-table" class="table table-striped table-bordered" data-source="<%= dataview_samples_superindex_url(format:"json") %>" >
        <thead>
        <tr>
          <th>INDIGO ID</th>
          <th>Sample Source</th>
          <th>Site ID</th>
          <th>Disease</th>
          <th>Sex</th>
          <th>Race</th>
          <th>Age of Onset</th>
          <th>Age at Sample</th>
          <th>Legacy KIR Genotype</th>
          <% if @disease == 'NMO' %>
            <th>AQP4 Antibodies</th>
          <% end %>

        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>